site_name: kallisto | bustools
site_description: Short and simple bioinformatics tutorials
site_author: A. Sina Booeshaghi
copyright: "Copyright &copy; 2021 - 2021 Pachterlab"
repo_url: https://github.com/pachterlab/kallistobustools
repo_name: pachterlab/kallistobustools
edit_uri: tree/master/tutorials/docs/

theme:
  name: material
  palette:
    scheme: default
    primary: teal
    accent: amber
  features:
  - search.suggest
  - search.highlight
  language: en

google_analytics: ["UA-142178789-1", "kallistobus.tools"]

markdown_extensions:
- toc:
    permalink: true
- admonition
- codehilite
- extra
- pymdownx.highlight:
    linenums: true
    linenums_style: pymdownx.inline
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.betterem:
    smart_enable: all

extra:
  social:
    - type: "github"
      icon: fontawesome/brands/github
      link: "https://github.com/pachterlab"
    - type: "twitter"
      icon: fontawesome/brands/twitter
      link: "https://twitter.com/sinabooeshaghi"

extra_css:
- css/custom.css

nav:
- Home: index.md
- Applications: applications.md
- Using kb:
  - Introduction: kb_usage/kb_usage.md
  - Building a reference: kb_usage/kb_ref.md
  - Quantifying a dataset: kb_usage/kb_count.md
- Tutorials: 
## Introduction
  - Introduction to single-cell RNA-seq:
    - Python: tutorials/scRNA-seq_intro/python/scRNA-seq_intro.md
  - Preprocessing & Quality Control:
    - Python: tutorials/kb_quality_control/python/kb_intro_1_python.md
    - R: tutorials/kb_quality_control/R/kb_intro_1_R.md
  - Getting started with analysis:
    - Python: tutorials/kb_getting_started/python/kb_intro_2_python.md
    - R: tutorials/kb_getting_started/R/kb_intro_2_R.md
## Analysis
  - Building & annotating an atlas:
    - Python: tutorials/kb_building_atlas/python/kb_analysis_0_python.md
    - R: tutorials/kb_building_atlas/R/kb_analysis_0_R.md
  - Pseudotime analysis:
    - R: tutorials/kb_pseudotime/R/slingshot/kb_slingshot.md
  - Single-nuclei RNA-seq:
    - Python: tutorials/kb_nucleus/python/kb_single_nucleus.md
  - RNA Velocity:
    - Python: tutorials/kb_velocity/python/kb_velocity.md
  - Feature barcode & multimodal data: 
    - Python: tutorials/kb_kite/python/kb_kite.md
## Other
  - Find & download data: tutorials/download_data/data_download.md
  - Build custom index: 
    - Python: tutorials/kb_custom_index/python/kb_transcriptome_index.md
  - Build RNA velocity index:
    - Python: tutorials/kb_velocity_index/python/kb_velocity_index.md
  - Aggregate multiple matrices:
    - Python: tutorials/kb_aggregate/python/kb_aggregating_count_matrices.md
  - Process multiple FASTQs:
    - Python: tutorials/kb_multiple_fastqs/python/kb_multiple_files.md
  - Processing multi-species data: 
    - Python: tutorials/kb_species_mixing/python/kb_species_mixing.md
    - R: tutorials/kb_species_mixing/R/kb_mixed_species_10x_v2.md
  - Pseudotime analysis (Monocle2):
    - R: tutorials/kb_pseudotime/R/monocle2/kb_monocle2.md
